
server:
  port: 5003
spring:
  application:
    name: catergory-Service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/Catergory_Service_db
    username: postgres
    password: 2006
    driver-class-name: org.postgresql.Driver


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka"