#spring.application.name=Booking-Service
#server.port=5005
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/Booking_Service_db
#spring.datasource.username=postgres
#spring.datasource.password=2006
#spring.datasource.driver-class-name=org.postgresql.Driver
server:
  port: 5005


spring:
  application:
    name: BOOKING-SERVICE
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/Booking_Services_db
    username: postgres
    password: 2006
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka"