
server:
  port: 5004
  tomcat:
    connection-timeout: 20000
    keep-alive-timeout: 60000
spring:
  application:
    name: SERVICE-OFFERING
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/Service_offering_db
    username: postgres
    password: 2006
    driver-class-name: org.postgresql.Driver


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka"